defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Soyeon Kim
subtitle: Data scientist

# Side Menu Links
menu:
  - text: Portfolio
    link: /
    icon: ""

  - text: Skills & Offers
    link: /skills-and-offers
    icon: ""

  - text: Contact Me
    link: /contact
    icon: ""

  - text: My Resume
    link: /resume
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: soyeonkim-blog.github.io
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/soyeon2019
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter


    
